# Generated by Django 4.0.4 on 2022-05-03 03:51

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import school.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Room Name')),
                ('maximum_seats', models.IntegerField(default=3)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='School Name')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('seat_id', models.CharField(max_length=100, verbose_name='Seat ID')),
                ('seat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.room', validators=[school.models.max_seats])),
            ],
            options={
                'unique_together': {('seat_id', 'seat_room')},
            },
        ),
        migrations.CreateModel(
            name='StudentsInRoomData',
            fields=[
                ('room_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Room Name')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(editable=False, max_length=100, verbose_name='Full Name')),
                ('roll_no', models.CharField(blank=True, editable=False, max_length=6, null=True)),
                ('on_date', models.DateField(editable=False)),
                ('email', models.EmailField(editable=False, max_length=254, verbose_name='Email Address')),
                ('room', models.CharField(default='', editable=False, max_length=100, verbose_name='Room Name')),
                ('school', models.CharField(default='', editable=False, max_length=100, verbose_name='School Name')),
                ('student_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.seat')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='room',
            name='room_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('roll_no', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('on_date', models.DateField()),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('student_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.seat')),
            ],
            options={
                'unique_together': {('student_seat', 'on_date')},
            },
        ),
    ]
